# Generated by Django 4.2.6 on 2023-11-28 16:21

import app_album_viewer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='media/default-cover.png', upload_to='media')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('artist', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('format', models.CharField(choices=[('DD', 'DigitalDownload'), ('CD', 'CD'), ('VINYL', 'Vinyl')], default='DD', max_length=5)),
                ('release_date', models.DateField(null=True, validators=[app_album_viewer.models.validate_release_date])),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_display_name', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('runtime', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_album_viewer.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_album_viewer.comment'),
        ),
    ]
