# Generated by Django 4.2.6 on 2023-12-05 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_album_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_album_viewer.album'),
        ),
    ]
